server:
  port: 8082

spring:
  application:
    name: profile-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/club_user
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true                        # ✅ correct level
    hibernate:
      ddl-auto: update
    properties:                           # ✅ correct level
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 500KB
      max-request-size: 500KB

  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis
      redis:
        time-to-live: 600000 # 10 min

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${random.value}

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

logging:
  level:
    root: INFO
    com.college.profile_management: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

springdoc:
  api-docs:
    enabled: true                         # ✅ explicit
    path: /v3/api-docs
  swagger-ui:
    enabled: true                         # ✅ explicit
    path: /swagger-ui.html

app:
  independent-service:
    url: http://INDEPENDENT-SERVICES/api
  user-service:
    url: http://USER-SERVICE/api