spring:
  application:
    name: profile-management-service

  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

  datasource:
    url: jdbc:postgresql://localhost:5432/club_user
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


